# Generated by Django 3.0.2 on 2020-02-20 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=8)),
                ('rating', models.CharField(max_length=3)),
                ('date_released', models.DateTimeField()),
                ('date_ending', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
                ('preview_photo', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=4000)),
                ('link', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Session_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('cinema', models.DecimalField(decimal_places=0, max_digits=3)),
                ('price', models.CharField(max_length=8)),
                ('booking_link', models.TextField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Movie_Info')),
            ],
        ),
    ]
