# Generated by Django 3.0.2 on 2020-02-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_info',
            name='preview_photo',
            field=models.CharField(max_length=100),
        ),
    ]
