# Generated by Django 3.0.2 on 2020-02-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_auto_20200220_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_info',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
