# Generated by Django 3.0.2 on 2020-02-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_auto_20200220_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_info',
            name='booking_link',
            field=models.TextField(default='/bookings/'),
        ),
        migrations.AlterField(
            model_name='session_info',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session_info',
            name='price',
            field=models.CharField(default='$14.00', max_length=8),
        ),
    ]
