# Generated by Django 3.0.2 on 2020-02-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0005_auto_20200220_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_info',
            name='booking_link',
        ),
        migrations.RemoveField(
            model_name='session_info',
            name='cinema',
        ),
        migrations.RemoveField(
            model_name='session_info',
            name='date',
        ),
        migrations.RemoveField(
            model_name='session_info',
            name='price',
        ),
        migrations.RemoveField(
            model_name='session_info',
            name='time',
        ),
        migrations.RemoveField(
            model_name='session_info',
            name='title',
        ),
    ]
