# Generated by Django 3.0.2 on 2020-02-20 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0006_auto_20200220_0235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session_Info',
        ),
    ]
